import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowUp, Pause, Play, ScanLine, Layers3, Box, Sparkles, X, Copy, Check } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '../components/ui/dialog';
import './style.css';

const projects = [
 {id:'01',name:'FunFocus',title:'让探索，回到真实世界。',type:'产品设计',meta:'儿童投影相机 · 2024',image:'funfocus',gallery:['funfocus-detail','funfocus-process'],desc:'将拍摄、投影与分享融入儿童相机，鼓励孩子记录生活，在真实的互动中发现乐趣。',role:'参与前期调研、用户研究及产品渲染。',award:'第十六届蓝桥杯视觉艺术大赛 · 广东省一等奖'},
 {id:'02',name:'与风相愈',title:'让每一个故事，都被听见。',type:'UI / 服务设计',meta:'一人一故事剧场 · 2024',image:'wind',gallery:['wind-flow','wind-ui'],desc:'面向漂泊青年的一人一故事剧场服务设计，通过故事表达与线下参与，建立人与人之间的情感连接。',role:'参与前期调研、线下访谈、UI 设计及物料设计。',award:'UXDA 入围奖 · 第13届未来设计师广东省一等奖'},
 {id:'03',name:'转来',title:'一盏茶里的，当代生活。',type:'产品 / UI 设计',meta:'茶具产品与数字体验',image:'tea-scene',gallery:['tea','tea-ui'],desc:'围绕饮茶场景展开产品与配套界面探索，将产品形态、使用体验和视觉语言串联起来。',role:'作品集展示：用户研究、造型探索、结构呈现及配套 UI。'},
 {id:'04',name:'STRAY SOUL',title:'共生共鸣，温柔有你。',type:'品牌 / 视觉设计',meta:'流浪共生品牌设计',image:'stray',gallery:[],desc:'围绕流浪动物与人的关系，以鲜明的橙色和亲切的角色语言，构建从标志到周边物料的品牌体验。',role:'作品集展示：品牌视觉、IP 形象及应用设计。'},
 {id:'05',name:'meowfit',title:'共享空间，也共享陪伴。',type:'产品设计',meta:'人宠共居家具',image:'meowfit',gallery:[],desc:'关注人与宠物共享的生活空间，通过家具设计连接日常使用与陪伴需求。',role:'作品集展示：用户研究、产品造型与场景渲染。'},
 {id:'06',name:'物理五韵',title:'让古代智慧，有了新面孔。',type:'IP / 视觉设计',meta:'中国古代物理智慧 · 2025',image:'physics',gallery:[],desc:'以力学、声学等五大领域为灵感，通过角色装束与道具再现历史场景，以现代设计语言传播中国古代科学。',role:'担任队长，主导 IP 角色设计，负责形象绘制、插画与海报排版。',award:'2025 米兰设计周 · 广东省三等奖'},
];
const experience=[['2026.03 — 2026.08','坦黎科技有限公司','APP 产品专员','用户体验痛点挖掘、需求文档、海外 C 端 APP 改版与 UI 方案落地。'],['2025.08 — 2025.11','汤臣倍健','设计实习生','产品包装、电商详情页与海外社媒内容设计，协同推进品牌视觉。'],['2024.07 — 2024.12','几何设计工作室','助教','考研手绘及设计理论教学辅导。']];
const skills=[{icon:ScanLine,en:'RESEARCH & INSIGHT',title:'从真实问题出发',body:'通过访谈、问卷与文献研究理解用户，把零散反馈转化为清晰的设计方向。',tags:['用户研究','需求分析','服务设计']},{icon:Layers3,en:'EXPERIENCE & INTERFACE',title:'让体验清晰、自然',body:'连接业务需求与用户任务，从信息架构到界面细节，协同研发推进设计落地。',tags:['UI 设计','交互逻辑','Figma']},{icon:Box,en:'PRODUCT & VISUAL',title:'在多种媒介中表达',body:'结合产品设计背景与视觉表达能力，让形态、材质、品牌与数字界面保持一致。',tags:['Rhino / KeyShot','品牌视觉','Ps / Ai']},{icon:Sparkles,en:'AI & EXPLORATION',title:'保持对新可能的好奇',body:'将 AI 设计作为持续探索的方向，关注生成式工具与产品、视觉和界面设计的结合。',tags:['AI 设计方向','创意探索','持续学习']}];

function App(){
 const [selected,setSelected]=useState(null),[copied,setCopied]=useState(''),[playing,setPlaying]=useState(true);const video=useRef(null);
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');if(m.matches){video.current?.pause();setPlaying(false)}},[]);
 async function copy(value,key){try{await navigator.clipboard.writeText(value);setCopied(key);setTimeout(()=>setCopied(''),2400)}catch{setCopied('failed')}}
 function toggleVideo(){if(!video.current)return;if(video.current.paused){video.current.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false))}else{video.current.pause();setPlaying(false)}}
 return <>
 <a className="skip" href="#about">跳到正文</a>
 <header className="nav wrap"><a className="wordmark" href="#home" aria-label="赵雪莲 首页">XUELIAN<span>®</span></a><nav aria-label="主导航"><a href="#about">关于我</a><a href="#work">精选作品 <sup>06</sup></a><a href="#strengths">我的优势</a></nav><a className="contact-nav" href="#contact">聊聊新想法 <ArrowUpRight size={16}/></a></header>
 <main>
 <section id="home" className="hero">
  <video ref={video} className="hero-video" autoPlay muted playsInline loop preload="auto" poster="/assets/hero-poster.jpg" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)}><source src="/assets/hero.mp4" type="video/mp4"/></video><div className="hero-shade"/>
  <div className="hero-content wrap"><p className="eyebrow"><span className="status-dot"/> XUELIAN ZHAO — DESIGN PORTFOLIO</p><h1>感知真实。<br/>设计<span className="outline">下一种</span>可能<span className="green">。</span></h1><div className="hero-intro"><p>你好，我是赵雪莲。<br/><span>产品设计师 / AI 设计师 / UI 设计师</span></p><a className="round-link" href="#work" aria-label="探索精选作品"><ArrowDown size={27}/></a></div></div>
  <div className="hero-bottom wrap"><span>以人的需求为起点，让想法成为体验。</span><div><button className="video-control" onClick={toggleVideo} aria-label={playing?'暂停背景视频':'播放背景视频'}>{playing?<Pause size={13}/>:<Play size={13}/>} MOTION {playing?'ON':'OFF'}</button><span className="small-index">SCROLL TO EXPLORE ↓</span></div></div>
 </section>
 <section id="about" className="about section wrap"><div className="section-top"><span className="eyebrow">01 / ABOUT ME</span><span className="muted">理性洞察，也感性表达。</span></div><div className="about-grid"><div className="portrait-block"><img src="/assets/portrait.webp" alt="赵雪莲的个人照片" loading="lazy"/><div className="portrait-caption"><span>赵雪莲</span><span>XUELIAN ZHAO ↗</span></div></div><div className="about-content"><p className="eyebrow green">DESIGN WITH CURIOSITY</p><h2>在真实需求与<br/><span className="muted">美好体验之间。</span></h2><p className="intro">我是赵雪莲，广东工业大学工业设计工程专业硕士在读。本科的产品设计训练，让我习惯从使用场景出发；产品、UI 与视觉项目的实践，让我更关注完整的用户体验。</p><p className="intro">我喜欢把复杂的问题梳理清楚，也愿意为一个细节反复推敲。期待用跨领域的视角，探索产品与 AI 设计的更多可能。</p><div className="stats"><div><b>06<span>精选</span></b><p>产品 / UI / 视觉项目</p></div><div><b>03<span>段</span></b><p>实习与教学经历</p></div><div><b>02<span>阶段</span></b><p>本科 → 硕士设计教育</p></div></div><a className="text-link" href="mailto:15084759837@163.com">15084759837@163.com <ArrowUpRight size={18}/></a></div></div><div className="experience"><div><p className="eyebrow">THE JOURNEY</p><h3>经历，塑造视角。</h3><div className="education"><span>2024.09 — 至今</span><p>广东工业大学 · 工业设计工程硕士</p><span>2020.09 — 2024.06</span><p>中南林业科技大学 · 产品设计本科</p></div></div><div>{experience.map(([date,company,role,desc])=><article className="experience-row" key={company}><time>{date}</time><div><h4>{company}<span>{role}</span></h4><p>{desc}</p></div></article>)}</div></div></section>
 <section id="work" className="work section wrap"><div className="section-top"><span className="eyebrow">02 / SELECTED WORK</span><span className="muted">2024 — 2025 · 作品选集</span></div><div className="heading-row"><h2>想法，有形。</h2><p>从物理产品到数字体验，<br/>每个项目都是一次新的观察。</p></div><div className="projects">{projects.map(p=><button key={p.id} className={'project project-'+p.id} onClick={()=>setSelected(p)} aria-label={'查看 '+p.name+' 项目详情'}><div className="project-image"><img src={'/assets/'+p.image+'.webp'} alt={p.name+' 项目设计展示'} loading="lazy"/><span className="project-type">{p.type}</span><span className="project-arrow"><ArrowUpRight size={24}/></span></div><div className="project-caption"><div><span className="project-id">/{p.id}</span><h3>{p.name}</h3><span className="project-meta">{p.meta}</span></div><p>{p.title}</p></div></button>)}</div></section>
 <section id="strengths" className="strengths section wrap"><div className="section-top"><span className="eyebrow">03 / WHAT I BRING</span><span className="muted">思考的广度，执行的深度。</span></div><div className="heading-row"><h2>不止一个视角。</h2><p>用研究理解问题，用设计连接可能。</p></div><div className="skill-grid">{skills.map((s,i)=><article className="skill" key={s.en}><div className="skill-top"><s.icon size={30} strokeWidth={1.1}/><span>0{i+1}</span></div><p className="eyebrow">{s.en}</p><h3>{s.title}</h3><p className="skill-body">{s.body}</p><div className="tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
 <section id="contact" className="contact"><div className="wrap contact-inner"><div className="section-top"><span className="eyebrow">04 / GET IN TOUCH</span><span className="availability"><span className="status-dot"/> 期待新的机会与合作</span></div><div className="contact-main"><p className="muted">下一个好想法，始于一次对话。</p><a className="contact-title" href="mailto:15084759837@163.com">LET’S TALK<ArrowUpRight strokeWidth={1}/></a><div className="contact-methods"><a href="mailto:15084759837@163.com"><span>EMAIL</span>15084759837@163.com <ArrowUpRight size={18}/></a><button onClick={()=>copy('z20x12l11','wechat')}><span>WECHAT</span>{copied==='wechat'?'已复制微信号':'z20x12l11'} {copied==='wechat'?<Check size={17}/>:<Copy size={17}/>}</button><a href="tel:15084759837"><span>PHONE</span>150 8475 9837 <ArrowUpRight size={18}/></a></div><p className="copy-status" aria-live="polite">{copied==='failed'?'复制未成功，请手动选择并复制微信号。':''}</p></div><footer><a className="wordmark" href="#home">XUELIAN<span>®</span></a><p>© {new Date().getFullYear()} 赵雪莲 · 保持好奇，持续创造。</p><a href="#home">BACK TO TOP <ArrowUp size={15}/></a></footer></div></section>
 </main>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="project-dialog" showCloseButton={false}>{selected&&<><div className="dialog-head"><span className="eyebrow">PROJECT / {selected.id}</span><DialogClose className="dialog-close" aria-label="关闭项目详情"><X/></DialogClose></div><DialogTitle className="dialog-title">{selected.name}</DialogTitle><DialogDescription className="dialog-description">{selected.desc}</DialogDescription><div className="role"><p>{selected.role}</p>{selected.award&&<p className="green">{selected.award}</p>}</div>{[selected.image,...selected.gallery].map((img,i)=><img className="detail-image" key={img} src={'/assets/'+img+'.webp'} alt={selected.name+' 设计展示 '+(i+1)} loading="lazy"/>)}</>}</DialogContent></Dialog>
 </>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
