import usePortfolioMotion from './usePortfolioMotion';
import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowUp, Pause, Play, ScanLine, Layers3, Box, Sparkles, X, Copy, Check, Mail } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '../components/ui/dialog';
import './style.css';
import Grainient from './Grainient';
import BorderGlow from './BorderGlow';
import PartyYouDetails, { PartyYouCover } from './PartyYou';

const projects = [
 {id:'01',detailPages:["zhuanlai-page-6", "zhuanlai-page-7", "zhuanlai-page-8", "zhuanlai-page-9", "zhuanlai-page-10", "zhuanlai-page-11", "zhuanlai-page-12", "zhuanlai-page-13", "zhuanlai-page-14", "zhuanlai-page-15", "zhuanlai-page-16", "zhuanlai-page-17", "zhuanlai-page-18", "zhuanlai-page-19", "zhuanlai-page-20", "zhuanlai-page-21", "zhuanlai-page-22", "zhuanlai-page-23", "zhuanlai-page-24", "zhuanlai-page-25"],category:'product',name:'转来·客家围楼文创灯具',title:'一盏灯里的，当代生活。',type:'产品 / UI 设计',meta:'客家围楼文创灯具与数字体验',image:'tea-scene',gallery:['tea','tea-ui'],desc:'以客家围楼为设计主题，展开文创灯具与配套界面探索，将建筑文化、产品形态与灯光体验串联起来。',role:'作品集展示：用户研究、造型探索、结构呈现及配套 UI。'},
 {id:'02',detailPages:["meowfit-page-28", "meowfit-page-29", "meowfit-page-30", "meowfit-page-31", "meowfit-page-32", "meowfit-page-33", "meowfit-page-34", "meowfit-page-35", "meowfit-page-36", "meowfit-page-37", "meowfit-page-38", "meowfit-page-39", "meowfit-page-40", "meowfit-page-41"],category:'product',name:'meowfit ·猫咪体重管理家具',title:'共享空间，也共享陪伴。',type:'产品设计',meta:'猫咪体重管理家具',image:'meowfit',gallery:[],desc:'关注猫咪体重管理与人宠共居场景，通过家具设计连接宠物健康管理、日常使用与陪伴需求。',role:'作品集展示：用户研究、产品造型与场景渲染。'},
 {id:'03',category:'product',name:'FunFocus',title:'让探索，回到真实世界。',type:'产品设计',meta:'儿童投影相机 · 2024',image:'funfocus',gallery:['funfocus-detail','funfocus-process'],detailPages:Array.from({length:14},(_,i)=>'funfocus-page-'+(44+i)),desc:'将拍摄、投影与分享融入儿童相机，鼓励孩子记录生活，在真实的互动中发现乐趣。',role:'参与前期调研、用户研究及产品渲染。',award:'第十六届蓝桥杯视觉艺术大赛 · 广东省一等奖'},
 {id:'04',detailPages:["wiremaster-page-60", "wiremaster-page-61", "wiremaster-page-62", "wiremaster-page-63", "wiremaster-page-64", "wiremaster-page-65", "wiremaster-page-66", "wiremaster-page-67", "wiremaster-page-68", "wiremaster-page-69", "wiremaster-page-70", "wiremaster-page-71", "wiremaster-page-72", "wiremaster-page-73"],category:'product',name:'WireMaster Box',title:'让每一根线，都有自己的位置。',type:'产品设计',meta:'数据线收纳产品',image:'wiremaster',gallery:['wiremaster-scene','wiremaster-use','wiremaster-package'],desc:'围绕日常数据线的收纳与取用需求，通过分区整理和绕线收纳，让桌面线材更有序。以不同配色与使用场景，探索收纳产品的功能与视觉表达。',role:'作品集展示：产品造型、使用场景、收纳细节、CMF 配色及包装设计。'},
 {id:'05',detailPages:["wind-page-23", "wind-page-24", "wind-page-25", "wind-page-26", "wind-page-27", "wind-page-28", "wind-page-29", "wind-page-30", "wind-page-31", "wind-page-32", "wind-page-33", "wind-page-34", "wind-page-35", "wind-page-36", "wind-page-37", "wind-page-38", "wind-page-39", "wind-page-40"],category:'ui',name:'与风相愈故事集',title:'让每一个故事，都被听见。',type:'UI / 服务设计',meta:'一人一故事剧场 · 2024',image:'wind',gallery:['wind-flow','wind-ui'],desc:'面向漂泊青年的一人一故事剧场服务设计，通过故事表达与线下参与，建立人与人之间的情感连接。',role:'参与前期调研、线下访谈、UI 设计及物料设计。',award:'UXDA 入围奖 · 第13届未来设计师广东省一等奖'},
 {id:'06',category:'ui',name:'PartyYou · 海外社交APP',title:'从相遇，到连接。',type:'UI / APP设计',meta:'海外社交 · 高保真界面',image:'partyyou',gallery:[],customDetail:'partyyou',desc:'海外社交 APP 体验优化项目，结合海外用户使用习惯搭建统一 UI 设计规范，完成多界面改版优化，提升页面整洁度与操作流畅度。',role:'项目内容：高保真界面、状态反馈、弹窗规范、色彩规范及登录动效。'},
 {id:'07',detailPages:["stray-page-5", "stray-page-6", "stray-page-7", "stray-page-8", "stray-page-9", "stray-page-10", "stray-page-11", "stray-page-12", "stray-page-13", "stray-page-14", "stray-page-15", "stray-page-16"],category:'visual',name:'Stray Soul流浪共生品牌',title:'共生共鸣，温柔有你。',type:'品牌 / 视觉设计',meta:'流浪共生品牌设计',image:'stray',gallery:[],desc:'围绕流浪动物与人的关系，以鲜明的橙色和亲切的角色语言，构建从标志到周边物料的品牌体验。',role:'作品集展示：品牌视觉、IP 形象及应用设计。'},
 {id:'08',detailPages:["physics-page-18", "physics-page-19", "physics-page-20", "physics-page-21"],category:'visual',name:'物理五韵IP设计',title:'让古代智慧，有了新面孔。',type:'IP / 视觉设计',meta:'中国古代物理智慧 · 2025',image:'physics',gallery:[],desc:'以力学、声学等五大领域为灵感，通过角色装束与道具再现历史场景，以现代设计语言传播中国古代科学。',role:'担任队长，主导 IP 角色设计，负责形象绘制、插画与海报排版。',award:'2025 米兰设计周 · 广东省三等奖'},
];
const researchCases=[{id:'01',category:'research',name:'民航机上餐饮体验优化研究',title:'从乘客与乘务员双侧视角，理解机上餐饮体验。',type:'用户研究 / 服务设计',meta:'GAMECO 合作项目',imageSrc:'/assets/aviation-research/page-01.jpg',gallery:[],detailSources:Array.from({length:20},(_,i)=>'/assets/aviation-research/page-'+String(i+1).padStart(2,'0')+'.jpg'),desc:'围绕窄体机经济舱机上餐饮体验，结合乘客与乘务员双侧研究，探索乘客用餐体验与乘务员备餐、服务操作的优化方向。',role:'研究内容：研究规划、访谈、问卷、数据分析与洞察整合。'}];
const displayedProjects=[...researchCases,...projects];
const projectCategories=[{id:'research',label:'用户研究',en:'USER RESEARCH'},{id:'product',label:'产品设计',en:'PRODUCT DESIGN'},{id:'ui',label:'UI设计',en:'UI DESIGN'},{id:'visual',label:'平面视觉设计',en:'GRAPHIC & VISUAL DESIGN'}];
const experience=[['2026.03 — 2026.08','坦黎科技有限公司','APP 产品专员','负责挖掘用户体验痛点，输出功能优化需求文档，结合业务调研提炼有效需求，跟进调整直至功能上线；\n同时参与海外 C 端 APP 产品改版优化工作，负责 UI 方案输出，协同研发完成落地迭代。'],['2025.08 — 2025.11','汤臣倍健','设计实习生','负责协助产品经理对接视觉设计需求，对接运营和乙方设计师协助视觉设计调整；\n根据需求进行产品包装、电商平台详情页、海外社媒视觉内容设计，满足品牌宣传和电商使用需求。'],['2024.07 — 2024.12','几何设计工作室','助教','负责考研学生手绘及理论教学辅导。']];
const skills=[{icon:ScanLine,en:'RESEARCH & INSIGHT',title:'从真实问题出发',body:'通过访谈、问卷与文献研究理解用户，把零散反馈转化为清晰的设计方向。',tags:['用户研究','需求分析','服务设计']},{icon:Layers3,en:'EXPERIENCE & INTERFACE',title:'让体验清晰、自然',body:'连接业务需求与用户任务，从信息架构到界面细节，协同研发推进设计落地。',tags:['UI 设计','交互逻辑','Figma']},{icon:Box,en:'PRODUCT & VISUAL',title:'在多种媒介中表达',body:'结合产品设计背景与视觉表达能力，让形态、材质、品牌与数字界面保持一致。',tags:['Rhino / KeyShot','品牌视觉','Ps / Ai']},{icon:Sparkles,en:'AI & EXPLORATION',title:'保持对新可能的好奇',body:'将 AI 设计作为持续探索的方向，关注生成式工具与产品、视觉和界面设计的结合。',tags:['AI 设计方向','创意探索','持续学习']}];

function App(){
 const [navFloating,setNavFloating]=useState(false);
 const hero=useRef(null);
 usePortfolioMotion();
 useEffect(()=>{
  const updateNavigation=()=>setNavFloating(!!hero.current && hero.current.getBoundingClientRect().bottom<=0);
  updateNavigation();
  window.addEventListener('scroll',updateNavigation,{passive:true});
  window.addEventListener('resize',updateNavigation);
  return ()=>{window.removeEventListener('scroll',updateNavigation);window.removeEventListener('resize',updateNavigation)};
 },[]);
 const [selected,setSelected]=useState(null),[copied,setCopied]=useState(''),[playing,setPlaying]=useState(false);const video=useRef(null);
 useEffect(()=>{const el=video.current;if(!el)return;el.muted=true;el.defaultMuted=true;el.playsInline=true;const m=matchMedia('(prefers-reduced-motion: reduce)');if(m.matches){el.pause();return;}el.play().catch(()=>setPlaying(false));},[]);
 async function copy(value,key){try{await navigator.clipboard.writeText(value);setCopied(key);setTimeout(()=>setCopied(''),2400)}catch{setCopied('failed')}}
 function toggleVideo(){if(!video.current)return;if(video.current.paused){video.current.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false))}else{video.current.pause();setPlaying(false)}}
 return <>
 <a className="skip" href="#about">跳到正文</a>
 <header className={`nav wrap${navFloating ? ' nav-floating' : ''}`}><a className="wordmark" href="#home" aria-label="赵雪莲 首页">XUELIAN<span>®</span></a><nav aria-label="主导航"><a href="#about">关于我</a><a href="#work">精选作品 <sup>{String(displayedProjects.length).padStart(2,'0')}</sup></a><a href="#strengths">我的优势</a></nav><a className="contact-nav" href="#contact" aria-label="联系我，前往联系方式">联系我 <Mail size={18} strokeWidth={1.5} aria-hidden="true"/></a></header>
 <div className="page-grainient" aria-hidden="true"><Grainient color1="#88B55A" color2="#090F0A" color3="#3A745D" timeSpeed={0.25} grainAmount={0.1} grainScale={0.6} grainAnimated contrast={1.5} saturation={0.65} zoom={0.9}/></div>
 <main>
 <section ref={hero} id="home" className="hero"><div className="opening-curtain" aria-hidden="true"/>
  <video key="user-background-v2" ref={video} className="hero-video" muted playsInline loop preload="metadata" poster="/assets/hero-current-poster.jpg" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)}><source src="/assets/hero-mobile-compatible.mp4" type="video/mp4"/></video><div className="hero-glass" aria-hidden="true"/><div className="hero-shade"/>
  <div className="hero-content wrap"><p className="eyebrow"><span className="status-dot"/> XUELIAN ZHAO — DESIGN PORTFOLIO</p><h1><span className="hero-title-line"><span>感知真实。</span></span><span className="hero-title-line"><span>设计<span className="outline">下一种</span>可能<span className="green">。</span></span></span></h1><div className="hero-intro"><p>你好，我是赵雪莲。<br/><span>产品设计师 / AI 设计师 / UI 设计师</span></p><a className="round-link" href="#work" aria-label="探索精选作品"><ArrowDown size={27}/></a></div></div>
  {!playing&&<button className="hero-play-fallback" onClick={toggleVideo}><Play size={16}/>播放背景视频</button>}<div className="hero-bottom wrap"><span>以人的需求为起点，让想法成为体验。</span><div><button className="video-control" onClick={toggleVideo} aria-label={playing?'暂停背景视频':'播放背景视频'}>{playing?<Pause size={13}/>:<Play size={13}/>} MOTION {playing?'ON':'OFF'}</button><span className="small-index">SCROLL TO EXPLORE ↓</span></div></div>
 </section>
 <section id="about" className="about section wrap"><div className="section-top"><span className="eyebrow">01 / ABOUT ME</span><span className="muted">理性洞察，也感性表达。</span></div><div className="about-grid"><div className="portrait-block"><img src="/assets/avatar-skills-glass.png" alt="赵雪莲的Q版形象，倚靠Figma、Axure、KeyShot、Photoshop、Illustrator和Rhino六个软件图标方块" loading="lazy"/><div className="portrait-caption"><span>赵雪莲</span><span>XUELIAN ZHAO ↗</span></div></div><div className="about-content"><p className="eyebrow green">DESIGN WITH CURIOSITY</p><h2>在真实需求与<br/><span className="muted">美好体验之间。</span></h2><p className="intro">我是赵雪莲，广东工业大学工业设计工程专业硕士在读。本科的产品设计训练，让我习惯从使用场景出发；产品、UI 与视觉项目的实践，让我更关注完整的用户体验。</p><p className="intro">我喜欢把复杂的问题梳理清楚，也愿意为一个细节反复推敲。期待用跨领域的视角，探索产品与 AI 设计的更多可能。</p><div className="stats"><div><b>{String(displayedProjects.length).padStart(2,'0')}<span>精选</span></b><p>产品 / UI / 视觉项目</p></div><div><b>03<span>段</span></b><p>实习与教学经历</p></div><div><b>02<span>阶段</span></b><p>本科 → 硕士设计教育</p></div></div><a className="text-link" href="mailto:15084759837@163.com">15084759837@163.com <ArrowUpRight size={18}/></a></div></div><div className="experience"><div><p className="eyebrow">THE JOURNEY</p><h3>经历，塑造视角。</h3><div className="education"><span>2024.09 — 至今</span><p>广东工业大学 · 工业设计工程硕士</p><span>2020.09 — 2024.06</span><p>中南林业科技大学 · 产品设计本科</p></div></div><div>{experience.map(([date,company,role,desc])=><article className="experience-row" key={company}><time>{date}</time><div><h4>{company}<span>{role}</span></h4><p>{desc}</p></div></article>)}</div></div></section>
 <section id="work" className="work section wrap"><div className="section-top"><span className="eyebrow">02 / SELECTED WORK</span><span className="muted">产品 / UI / 视觉 · 作品选集</span></div><div className="heading-row"><h2>想法，有形。</h2><p>从物理产品到数字体验，<br/>每个项目都是一次新的观察。</p></div><nav className="work-categories" aria-label="作品分类">{projectCategories.map(category=><a key={category.id} href={'#work-'+category.id}>{category.label}<span>{String(displayedProjects.filter(p=>p.category===category.id).length).padStart(2,'0')}</span></a>)}</nav>{projectCategories.map(category=><section className="work-group" id={'work-'+category.id} key={category.id} aria-labelledby={'heading-'+category.id}><div className="work-group-heading"><h3 id={'heading-'+category.id}>{category.label}<span>{String(displayedProjects.filter(p=>p.category===category.id).length).padStart(2,'0')}</span></h3><p>{category.en}</p></div><div className="projects">{displayedProjects.filter(p=>p.category===category.id).map(p=><BorderGlow key={p.category+'-'+p.id} className="project-glow"><button className={'project project-'+p.id} onClick={()=>setSelected(p)} aria-label={'查看 '+p.name+' 项目详情'}><div className="project-image">{p.customDetail==='partyyou'?<PartyYouCover/>:<img src={p.imageSrc ?? '/assets/'+p.image+'.webp'} alt={p.name+' 项目设计展示'} loading="lazy"/>}<span className="project-type">{p.type}</span><span className="project-arrow"><ArrowUpRight size={24}/></span></div><div className="project-caption"><div><span className="project-id">{p.id}</span><h3>{p.name}</h3><span className="project-meta">{p.meta}</span></div><p>{p.title}</p></div></button></BorderGlow>)}</div></section>)}</section>
 <section id="strengths" className="strengths section wrap"><div className="section-top"><span className="eyebrow">03 / WHAT I BRING</span><span className="muted">思考的广度，执行的深度。</span></div><div className="heading-row"><h2>不止一个视角。</h2><p>用研究理解问题，用设计连接可能。</p></div><div className="skill-grid">{skills.map((s,i)=><BorderGlow className="skill-glow" key={s.en}><article className="skill"><div className="skill-top"><s.icon size={30} strokeWidth={1.1}/><span>0{i+1}</span></div><p className="eyebrow">{s.en}</p><h3>{s.title}</h3><p className="skill-body">{s.body}</p><div className="tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div></article></BorderGlow>)}</div></section>
 <section id="contact" className="contact"><div className="wrap contact-inner"><div className="section-top"><span className="eyebrow">04 / THANK YOU</span><span className="availability"><span className="status-dot"/> 期待新的机会与合作</span></div><div className="contact-main"><div className="closing-layout"><div className="closing-photo"><img src="/assets/closing-lifestyle.jpg" alt="赵雪莲的生活照" loading="lazy"/></div><div className="closing-message"><p className="eyebrow closing-kicker">感谢观看我的作品集</p><h2 className="closing-title">THANK YOU<span className="closing-period" aria-label="。"/></h2><p className="closing-note">感谢你的时间与关注，期待与你交流新的设计可能。</p><div className="closing-wechat"><img src="/assets/wechat-qr.png" alt="赵雪莲的微信二维码" loading="lazy"/><div><span className="eyebrow green">LET’S CONNECT</span><p>扫码添加我的微信</p><span>z20x12l11</span></div></div></div></div><div className="contact-methods"><a href="mailto:15084759837@163.com"><span>EMAIL</span>15084759837@163.com <ArrowUpRight size={18}/></a><button onClick={()=>copy('z20x12l11','wechat')}><span>WECHAT</span>{copied==='wechat'?'已复制微信号':'z20x12l11'} {copied==='wechat'?<Check size={17}/>:<Copy size={17}/>}</button><a href="tel:15084759837"><span>PHONE</span>150 8475 9837 <ArrowUpRight size={18}/></a></div><p className="copy-status" aria-live="polite">{copied==='failed'?'复制未成功，请手动选择并复制微信号。':''}</p></div><footer><a className="wordmark" href="#home">XUELIAN<span>®</span></a><p>© {new Date().getFullYear()} 赵雪莲 · 保持好奇，持续创造。</p><a href="#home">BACK TO TOP <ArrowUp size={15}/></a></footer></div></section>
 </main>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="project-dialog" showCloseButton={false}>{selected&&<><div className="dialog-head"><span className="eyebrow">{selected.category==='research'?'RESEARCH':'PROJECT'} / {selected.id}</span><DialogClose className="dialog-close" aria-label="关闭项目详情"><X/></DialogClose></div><DialogTitle className="dialog-title">{selected.name}</DialogTitle><DialogDescription className="dialog-description">{selected.desc}</DialogDescription><div className="role"><p>{selected.role}</p>{selected.award&&<p className="green">{selected.award}</p>}</div>{selected.customDetail==='partyyou'?<PartyYouDetails/>:(selected.detailSources ?? selected.detailPages ?? [selected.image,...selected.gallery]).map((img,i)=><img className="detail-image" key={img} src={selected.detailSources?img:'/assets/'+img+'.webp'} alt={selected.name+' 设计展示 '+(i+1)} loading="lazy"/>)}</>}</DialogContent></Dialog>
 </>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);


